---
- name: Install & run docker
  include: install_docker.yml

- name: Run DB-server
  shell: docker stop `docker ps -a | grep mysql:5.7.8 | awk '{print $1}'` ; docker rm `sudo docker ps -a | grep mysql:5.7.8 | awk '{print $1}'` ; docker run -d -e MYSQL_USER=petclinic -e MYSQL_PASSWORD=petclinic -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=petclinic -p 3306:3306 mysql:5.7.8

- name: kill runned project
  shell: kill -9 `ps -aux | grep spring| grep -v grep | awk '{print $2}'` 2>/dev/null ; sleep 10s
  ignore_errors: yes

- name: Run app with MySQL container
  #shell: java -jar target/*.jar &
  shell: 'java -Dspring.profiles.active=mysql -jar target/*.jar &'
  args:
    chdir: /opt/spring-petclinic/
