version: "3"
services:
    java:
      build:
          context: ./
          dockerfile: java-app
      container_name: java-app
      ports:
          - "8080:8080"
      networks:
          - default
      depends_on:
       - "mysql"

    mysql:
      image: mysql:5.7
      container_name: mysql-app
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
        - MYSQL_USER=petclinic
        - MYSQL_PASSWORD=petclinic
        - MYSQL_DATABASE=petclinic
      volumes:
        - "./conf.d:/etc/mysql/conf.d:ro"
      networks:
            - default
