---
- name: Add config directory
  shell: mkdir -p $PWD/nginx_config

- name: Check run nginx container
  shell: docker stop nginx &&  docker rm nginx || echo 'nginx is not running';

- name: Wipe volumes
  shell: yes | docker volume prune

- name: Add domain nginx config
  template:
    src: conf.nossl.loadbalanser.template.j2
    dest: $PWD/nginx_config/{{ domain }}.conf.template
    mode: 644

- name: Check run nginx container
  shell: docker stop nginx &&  docker rm nginx || echo 'nginx is not running';

- name: Run nginx container
  shell: OPEN_CURLY="{";docker run -d --name nginx --restart always \
            -e NGINX_HOST={{ domain }} \
            -e PROXY_ADDRESS={{ proxy_ip }} \
            -e PROXY_PORT={{ proxy_port }} \
            -e PROXY_ADDRESS2={{ proxy_ip2 }} \
            -e PROXY_PORT2={{ proxy_port2 }} \
            -p 80:80 \
            --log-driver=json-file \
            --log-opt tag="$OPEN_CURLY{.ImageName}}|$OPEN_CURLY{.Name}}|$OPEN_CURLY{.ImageFullID}}|$OPEN_CURLY{.FullID}}" \
            -v $PWD/nginx_config:/etc/nginx/templates \
            nginx
