version: '3'

services:
  registry:
    container_name: docker-registry
    restart: always
    image: registry:2.7.0
    environment:
       - REGISTRY_AUTH=htpasswd
       - REGISTRY_AUTH_HTPASSWD_REALM="ExampleRealm"
       - REGISTRY_AUTH_HTPASSWD_PATH=/auth/.htpasswd
    volumes:
       - /opt/docker_registry/data:/var/lib/registry
       - /opt/docker_registry/auth:/auth
    ports:
       - "5000:5000"


  nginx:
    container_name: nginx-docker-registry
    restart: always
    image: nginx
    environment:
       - NGINX_HOST=docker-registry.domain
       - PROXY_ADDRESS=docker-registry
       - PROXY_PORT=5000
    volumes:
       - "./nginx_config:/etc/nginx/templates"
       - "/etc/letsencrypt:/etc/letsencrypt"
    ports:
       - "80:80"
       - "443:443"
