---
- name: Update system
  dnf: name="*" state=latest

- name: install packages
  dnf: name={{ packages }} state=present
  vars:
    packages:
      - maven
      - java-11-openjdk
      - git

- name: Install & run docker
  include: install_docker.yml
