global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "node_down.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 8s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx-exporter'
    scrape_interval: 8s
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'nginx-lua'
    scrape_interval: 8s
    static_configs:
      - targets: ['nginx-lua:9145']

  - job_name: 'loki'
    scrape_interval: 8s
    static_configs:
      - targets: ['loki:3100']
